name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deploy script
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        REPO_URL: ${{ secrets.REPO_URL }}
        APP_DIR: ${{ secrets.APP_DIR }}
        DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
        SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}
      run: |
        chmod +x deploy.sh
        ./deploy.sh
